# -*- coding: utf-8 -*-
"""02_screening_model.ipynb (Ryan)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1InWSoGdBth7Lw5z9Km8u8H5JS33sjbxv
"""



"""
CRBN (Cereblon) Bioactivity Pipeline
=====================================
Pulls all bioactivity records for the CRBN target from ChEMBL (EMBL-EBI),
converts each compound's SMILES into a 2048-bit Morgan fingerprint, and
labels each record as a binder (1) or non-binder (0) based on a
Ki/IC50/EC50/Kd potency threshold.

Outputs:
    X : np.ndarray, shape (n_valid_records, 2048)  -- fingerprint matrix
    Y : np.ndarray, shape (n_valid_records,)        -- binder labels (0/1)

Saved to disk as X_crbn_fingerprints.npy and Y_crbn_binders.npy
"""

import requests
import numpy as np
from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit import RDLogger

RDLogger.DisableLog("rdApp.*")  # silence RDKit SMILES parsing warnings

CHEMBL_BASE_URL = "https://www.ebi.ac.uk/chembl/api/data"
ACTIVITY_THRESHOLD_NM = 10000  # binder cutoff in nanomolar (adjust as needed)
FINGERPRINT_BITS = 2048
FINGERPRINT_RADIUS = 2


# ---------------------------------------------------------------------------
# Step 1: Find the CRBN target in ChEMBL
# ---------------------------------------------------------------------------
def get_crbn_target_id():
    """
    Search ChEMBL (EMBL-EBI) for the CRBN (Cereblon) target and return
    its ChEMBL target ID and preferred name.
    """
    url = f"{CHEMBL_BASE_URL}/target/search"
    params = {"q": "CRBN", "format": "json"}
    resp = requests.get(url, params=params)
    resp.raise_for_status()
    data = resp.json()

    targets = data.get("targets", [])
    if not targets:
        raise ValueError("No CRBN target found in ChEMBL")

    # Prefer a single-protein human target
    for t in targets:
        if t.get("target_type") == "SINGLE PROTEIN" and t.get("organism") == "Homo sapiens":
            return t["target_chembl_id"], t["pref_name"]

    # fallback: first hit
    return targets[0]["target_chembl_id"], targets[0]["pref_name"]


# ---------------------------------------------------------------------------
# Step 2: Pull every bioactivity record against CRBN
# ---------------------------------------------------------------------------
def fetch_all_activities(target_chembl_id, batch_size=1000):
    """
    Page through ChEMBL's /activity endpoint to retrieve all bioactivity
    records for the given target (e.g. ~1432 records for CRBN).
    """
    url = f"{CHEMBL_BASE_URL}/activity"
    all_records = []
    offset = 0

    while True:
        params = {
            "target_chembl_id": target_chembl_id,
            "format": "json",
            "limit": batch_size,
            "offset": offset,
        }
        resp = requests.get(url, params=params)
        resp.raise_for_status()
        data = resp.json()

        activities = data.get("activities", [])
        if not activities:
            break

        all_records.extend(activities)

        total = data["page_meta"]["total_count"]
        offset += batch_size
        if offset >= total:
            break

    return all_records


# ---------------------------------------------------------------------------
# Step 3: Label each record as binder / non-binder
# ---------------------------------------------------------------------------
def label_binder(record, threshold_nm=ACTIVITY_THRESHOLD_NM):
    """
    Determine binder (1) / non-binder (0) / unknown (None) from a single
    ChEMBL activity record.

    Applies the same threshold to Ki, IC50, EC50, and Kd values reported
    in nanomolar units. Falls back to ChEMBL's curated activity_comment
    field ("active"/"inactive") when no usable numeric value is present.

    NOTE: Ki/Kd are direct binding affinity measurements, while IC50/EC50
    are assay-dependent functional readouts -- they are not strictly
    equivalent. This function currently treats them the same; consider
    restricting to Ki/Kd only if you want a stricter "binder" definition.
    """
    std_type = (record.get("standard_type") or "").upper()
    std_value = record.get("standard_value")
    std_units = (record.get("standard_units") or "").lower()

    binding_types = {"KI", "IC50", "EC50", "KD"}

    if std_type in binding_types and std_value is not None and std_units == "nm":
        try:
            value = float(std_value)
        except (TypeError, ValueError):
            return None
        return 1 if value <= threshold_nm else 0

    # fallback: curated text label
    comment = (record.get("activity_comment") or "").lower()
    if "active" in comment and "inactive" not in comment:
        return 1
    if "inactive" in comment:
        return 0

    return None  # not enough info to label


# ---------------------------------------------------------------------------
# Step 4: SMILES -> molecule -> molecular weight -> fingerprint
# ---------------------------------------------------------------------------
def process_smiles(smiles, n_bits=FINGERPRINT_BITS, radius=FINGERPRINT_RADIUS):
    """
    Convert a SMILES string into:
      - an RDKit molecule
      - molecular weight (stored as a property on the molecule)
      - a fingerprint (n_bits-length numpy array of 0s/1s)

    Returns (mol, mol_weight, fingerprint_array), or (None, None, None)
    if the SMILES is invalid.
    """
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None, None, None

    from rdkit.Chem import Descriptors
    mol_weight = Descriptors.MolWt(mol)
    mol.SetDoubleProp("molecular_weight", mol_weight)

    fp = AllChem.GetMorganFingerprintAsBitVect(mol, radius=radius, nBits=n_bits)
    fp_array = np.zeros((n_bits,), dtype=int)
    Chem.DataStructs.ConvertToNumpyArray(fp, fp_array)

    return mol, mol_weight, fp_array


def smiles_to_fingerprint(smiles, n_bits=FINGERPRINT_BITS, radius=FINGERPRINT_RADIUS):
    """Lightweight version used when only the fingerprint (not MW) is needed."""
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None
    fp = AllChem.GetMorganFingerprintAsBitVect(mol, radius=radius, nBits=n_bits)
    arr = np.zeros((n_bits,), dtype=int)
    Chem.DataStructs.ConvertToNumpyArray(fp, arr)
    return arr


# ---------------------------------------------------------------------------
# Main pipeline: build X (fingerprints) and Y (binder labels)
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    # --- find CRBN target ---
    target_id, target_name = get_crbn_target_id()
    print(f"Target: {target_name} ({target_id})")

    # --- pull all bioactivity records ---
    records = fetch_all_activities(target_id)
    print(f"Total activity records pulled: {len(records)}")

    X_rows = []
    Y_labels = []
    skipped_no_smiles = 0
    skipped_no_label = 0
    skipped_bad_smiles = 0

    for record in records:
        smiles = record.get("canonical_smiles")
        if not smiles:
            skipped_no_smiles += 1
            continue

        label = label_binder(record)
        if label is None:
            skipped_no_label += 1
            continue

        fp = smiles_to_fingerprint(smiles)
        if fp is None:
            skipped_bad_smiles += 1
            continue

        X_rows.append(fp)
        Y_labels.append(label)

    X = np.array(X_rows)    # shape: (n_valid_records, 2048)
    Y = np.array(Y_labels)  # shape: (n_valid_records,)

    print(f"\nSkipped (no SMILES): {skipped_no_smiles}")
    print(f"Skipped (no activity label): {skipped_no_label}")
    print(f"Skipped (invalid SMILES): {skipped_bad_smiles}")

    print(f"\nX shape: {X.shape}")
    print(f"Y shape: {Y.shape}")
    print(f"Binders (Y=1): {int(Y.sum())}")
    print(f"Non-binders (Y=0): {int((Y == 0).sum())}")

    # --- save for downstream ML use ---
    np.save("X_crbn_fingerprints.npy", X)
    np.save("Y_crbn_binders.npy", Y)
    print("\nSaved X_crbn_fingerprints.npy and Y_crbn_binders.npy")

"""
CRBN Binder Classifier -- Random Forest, 80/20 Held-Out Split
==================================================================================
Approach:
  1. Split data: 80% train / 20% test (held out, untouched until the end).
  2. Train a Random Forest on the full 80% training set.
  3. Evaluate that model once on the untouched 20% test set (ROC/AUC on
     true held-out data).

(Earlier version also ran Leave-One-Out CV within the training set --
dropped because it trains one Random Forest per training sample, which
was too slow to be worth it; the held-out test set alone already gives an
unbiased AUC estimate.)
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_curve, roc_auc_score, classification_report, confusion_matrix

RANDOM_STATE = 42
TEST_SIZE = 0.20        # 20% held out as final test set
N_ESTIMATORS = 200


def load_data():
    X = np.load("X_crbn_fingerprints.npy")
    Y = np.load("Y_crbn_binders.npy")
    return X, Y


def evaluate(y_true, y_pred, y_proba, label=""):
    print(f"\nClassification report ({label}):")
    print(classification_report(y_true, y_pred, target_names=["Non-binder", "Binder"]))

    print(f"Confusion matrix ({label}):")
    print(confusion_matrix(y_true, y_pred))

    auc_score = roc_auc_score(y_true, y_proba)
    print(f"\n{label} AUC score: {auc_score:.4f}")

    return auc_score


def plot_roc(y_true, y_proba, auc_score, title, filename):
    fpr, tpr, _ = roc_curve(y_true, y_proba)

    plt.figure(figsize=(6, 6))
    plt.plot(fpr, tpr, color="darkorange", lw=2, label=f"ROC curve (AUC = {auc_score:.3f})")
    plt.plot([0, 1], [0, 1], color="navy", lw=1, linestyle="--", label="Random guess")
    plt.xlim([0.0, 1.0])
    plt.ylim([0.0, 1.05])
    plt.xlabel("False Positive Rate")
    plt.ylabel("True Positive Rate")
    plt.title(title)
    plt.legend(loc="lower right")
    plt.tight_layout()
    plt.savefig(filename, dpi=150)
    print(f"Saved ROC curve to {filename}")


if __name__ == "__main__":
    X, Y = load_data()
    print(f"Loaded X: {X.shape}, Y: {Y.shape}\n")

    # --- Step 1: 80/20 split ---
    X_train, X_test, y_train, y_test = train_test_split(
        X, Y,
        test_size=TEST_SIZE,
        random_state=RANDOM_STATE,
        stratify=Y
    )
    print(f"Train set: {X_train.shape[0]} samples ({1 - TEST_SIZE:.0%})")
    print(f"Test set:  {X_test.shape[0]} samples ({TEST_SIZE:.0%})\n")

    # --- Step 2: train final model on full training set ---
    final_clf = RandomForestClassifier(
        n_estimators=N_ESTIMATORS,
        random_state=RANDOM_STATE,
        n_jobs=-1,
        class_weight="balanced"
    )
    final_clf.fit(X_train, y_train)

    # --- Step 3: evaluate final model on untouched 20% test set ---
    test_pred = final_clf.predict(X_test)
    test_proba = final_clf.predict_proba(X_test)[:, 1]
    test_auc = evaluate(y_test, test_pred, test_proba, label="Held-out Test Set")
    plot_roc(
        y_test, test_proba, test_auc,
        title="ROC Curve -- CRBN Binder (Held-out 20% Test Set)",
        filename="crbn_roc_curve_test.png"
    )

    print("\n=== Summary ===")
    print(f"Held-out Test AUC:  {test_auc:.4f}")